name: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.name
partial: product_review
tabs:
    fields:
        product_name:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.detail
            label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.product_name

        product_description:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.detail
            label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.product_description

        product_info_url:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.detail
            label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.product_info_url

        product_buy_store:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.detail
            label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.product_buy_store

        product_buy_url:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.detail
            label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.product_buy_url

        product_rating:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.detail
            label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.product_rating
            type: dropdown
            options:
                1: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.rating_1
                2: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.rating_2
                3: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.rating_3
                4: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.rating_4
                5: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.rating_5

        product_intro:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.introduction
            type: richeditor
            size: huge

        product_review_body:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.review_body
            type: richeditor
            size: huge

        product_images:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.images
            type: repeater
            form:
                fields:
                    image:
                        label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.image
                        type: mediafinder
                    alt_text:
                        label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.alt_text
                    caption:
                        label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.caption

        product_positives:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.positives
            type: repeater
            form:
                fields:
                    reason:
                        label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.reason

        product_negatives:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.negatives
            type: repeater
            form:
                fields:
                    reason:
                        label: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.labels.reason

        product_verdict:
            tab: themes.dynamedia-postsdemo::lang.postbody_templates.product_review.tabs.verdict
            type: richeditor
            size: huge


